# Generated by Django 4.1.7 on 2023-02-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='owner',
        ),
    ]
