# Generated by Django 4.1.7 on 2023-02-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.CreateModel(
            name='SongImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/song/images')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='musics.song')),
            ],
        ),
    ]
