# Generated by Django 4.1.7 on 2023-02-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/author/images'),
        ),
    ]
